# K-means clustering

In [1]:
import math
import numpy as np

In [2]:

def euclidean_distance(x, y):

    return np.sqrt(np.sum(np.power(x-y,2)))


def centroid():
    print("hello")
    
def print_tables(i, mtx, points):
    print("ITERATION: "+str(i+1))
    print("\nCentroids")
    print(list(np.round(points,1)))
    print("\nTABLE")
    print(np.round(mtx,1))
    print("\nMin Value")
    print(mtx.min(axis=1))
    print("\nIndex of Min Points ")
    print(mtx.argmin(axis=1))
    print("\n======================\n")

def calc_centroid(d_set, mtx):
    points = [np.zeros((0,d_set.shape[1]))]*d_set.shape[1]
    for i,j in enumerate(mtx.argmin(axis=1)):
        points[j] = np.vstack((points[j], d_set[i]))
    centriods = np.zeros((d_set.shape[1],d_set.shape[1]))
    for i, point in enumerate(points) :
        centriods[i]=(point.mean(axis=0))
    return np.round(centriods,1)
            
        
def K_means(NumberOfIteration, dataset, initial_points):
    points = initial_points
    for i in range(NumberOfIteration):
        distance_to_centroid = np.zeros((len(dataset), len(points)))
        for j, point in enumerate(points) :
            for k, data in enumerate(dataset):
                distance_to_centroid[k][j]= round(euclidean_distance(point,data),3)
        print_tables(i, distance_to_centroid, points)
        
        points = calc_centroid(dataset,distance_to_centroid)

# Usage

# Exercise 10 clustering

<img src="images/knn1.png"/>

<img src="images/knn2.png"/>

In [3]:
#total number of iteration

NumberOfIteration = 2
#data set
dataset = np.matrix([
    [1.0,1.0],
    [1.5,2.0],
    [3.0,4.0],
    [5.0,7.0],
    [3.5,5.0],
    [4.5,5.0],
    [3.5,4.5],
])
#initial points
points = np.matrix([[1.0, 1.0], [5.0, 7.0]])


K_means(NumberOfIteration, dataset,points)

ITERATION: 1

Centroids
[array([ 1.,  1.]), array([ 5.,  7.])]

TABLE
[[ 0.   7.2]
 [ 1.1  6.1]
 [ 3.6  3.6]
 [ 7.2  0. ]
 [ 4.7  2.5]
 [ 5.3  2.1]
 [ 4.3  2.9]]

Min Value
[ 0.     1.118  3.606  0.     2.5    2.062  2.915]

Index of Min Points 
[0 0 0 1 1 1 1]


ITERATION: 2

Centroids
[array([ 1.8,  2.3]), array([ 4.1,  5.4])]

TABLE
[[ 1.5  5.4]
 [ 0.4  4.3]
 [ 2.1  1.8]
 [ 5.7  1.8]
 [ 3.2  0.7]
 [ 3.8  0.6]
 [ 2.8  1.1]]

Min Value
[ 1.526  0.424  1.78   1.836  0.721  0.566  1.082]

Index of Min Points 
[0 0 1 1 1 1 1]


